// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenu() {
  return window['go']['main']['App']['GetMenu']();
}

export function GetSchedule() {
  return window['go']['main']['App']['GetSchedule']();
}

export function OpenBjWithCookie(arg1) {
  return window['go']['main']['App']['OpenBjWithCookie'](arg1);
}
