// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';

export function GetMenu():Promise<any>;

export function GetSchedule():Promise<github.Schedule>;
