// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {selenium} from '../models';
import {github} from '../models';

export function GenerateCookieForBj():Promise<Array<selenium.Cookie>>;

export function GenerateCookieForPg():Promise<Array<selenium.Cookie>>;

export function GetMenu():Promise<any>;

export function GetSchedule():Promise<github.ScheduleList>;

export function OpenBjWithCookie(arg1:string):Promise<void>;
