// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProblem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProblem'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseProgram() {
  return window['go']['main']['App']['CloseProgram']();
}

export function CloseSeleniumBrowser() {
  return window['go']['main']['App']['CloseSeleniumBrowser']();
}

export function GetGithubRepositoryBjSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetGithubRepositoryBjSource'](arg1, arg2, arg3, arg4);
}

export function GetGithubRepositoryPgSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetGithubRepositoryPgSource'](arg1, arg2, arg3, arg4);
}

export function GetMenu() {
  return window['go']['main']['App']['GetMenu']();
}

export function GetPgSourceData(arg1) {
  return window['go']['main']['App']['GetPgSourceData'](arg1);
}

export function GetSchedule() {
  return window['go']['main']['App']['GetSchedule']();
}

export function IsBjLoggedIn(arg1) {
  return window['go']['main']['App']['IsBjLoggedIn'](arg1);
}

export function IsChromeRunning() {
  return window['go']['main']['App']['IsChromeRunning']();
}

export function IsPgLoggedIn(arg1) {
  return window['go']['main']['App']['IsPgLoggedIn'](arg1);
}

export function IsSubmittedCodeCorrect(arg1) {
  return window['go']['main']['App']['IsSubmittedCodeCorrect'](arg1);
}

export function NavigateToBjLoginPage() {
  return window['go']['main']['App']['NavigateToBjLoginPage']();
}

export function NavigateToBjProblemWithCookie(arg1) {
  return window['go']['main']['App']['NavigateToBjProblemWithCookie'](arg1);
}

export function NavigateToPgLoginPage() {
  return window['go']['main']['App']['NavigateToPgLoginPage']();
}

export function UploadBjSourceToGithub(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadBjSourceToGithub'](arg1, arg2, arg3, arg4);
}

export function UploadPgSourceToGithub(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadPgSourceToGithub'](arg1, arg2, arg3, arg4, arg5, arg6);
}
